"""
Generate the README's Results section from the artifacts, and check it stayed true.

Why this exists
---------------
The README advertised "AUC 0.789–0.859 across 5 segments" and gave a
five-row table of per-segment AUCs. The committed models' holdout AUCs at the
time were 0.572–0.674. The customer *counts* in that same table matched the
current dataset exactly, so the table had been half-updated: the rows were
refreshed when the project moved to Cell2Cell and the AUCs were carried over
from an earlier run on different data.

That is not carelessness so much as an inevitability. A number written into
prose cannot update itself, and nothing in the repository could tell that it had
stopped being true — the models were fine, the pipeline was fine, the tests were
green. The only defence is to stop writing the numbers by hand.

So the Results section is generated from `models/segment_models.pkl` and
`data/processed/uplift.parquet`, and CI runs `--check` to fail the build if the
committed README no longer matches what the artifacts say.

Usage
-----
    python scripts/readme_metrics.py --write    # regenerate the section
    python scripts/readme_metrics.py --check    # exit non-zero on drift (CI)
    python scripts/readme_metrics.py            # print the numbers
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

README = os.path.join(ROOT, "README.md")
START = "<!-- BEGIN GENERATED RESULTS -->"
END = "<!-- END GENERATED RESULTS -->"


def load() -> tuple[dict, pd.DataFrame, dict, dict]:
    import joblib  # noqa: PLC0415 — after sys.path is set up

    models_dir = os.path.join(ROOT, "models")
    segment_models = joblib.load(os.path.join(models_dir, "segment_models.pkl"))
    stability = joblib.load(os.path.join(models_dir, "stability.pkl"))
    uplift_metrics = joblib.load(os.path.join(models_dir, "uplift_metrics.pkl"))
    df = pd.read_parquet(os.path.join(ROOT, "data", "processed", "uplift.parquet"))
    return segment_models, df, stability, uplift_metrics


def build_section() -> str:
    segment_models, df, stability, uplift = load()

    with open(os.path.join(ROOT, "models", "pipeline_meta.json"), encoding="utf-8") as fh:
        meta = json.load(fh)

    metrics = [md["metrics"] for md in segment_models.values() if md]
    metrics.sort(key=lambda m: m["holdout_auc"], reverse=True)

    mean_holdout = float(np.mean([m["holdout_auc"] for m in metrics]))
    mean_train = float(np.mean([m["train_auc"] for m in metrics]))
    brier_raw = float(np.mean([m["holdout_brier_uncalibrated"] for m in metrics]))
    brier_cal = float(np.mean([m["holdout_brier"] for m in metrics]))

    churn_by_seg = df.groupby("Segment")["Churn"].mean()
    counts = df["Segment"].value_counts()

    rows = []
    for m in metrics:
        seg = m["segment"]
        rows.append(
            f"| {seg} | {counts[seg]:,} | {churn_by_seg[seg] * 100:.1f}% | "
            f"**{m['holdout_auc']:.3f}** | {m['train_auc']:.3f} | "
            f"{m['holdout_brier_uncalibrated']:.4f} → {m['holdout_brier']:.4f} | "
            f"{m['best_iteration']} |"
        )

    types = df["CustomerType"].value_counts()
    tiers = df["RiskTier"].value_counts()
    direction = uplift.get("direction_check", {})

    return f"""{START}
<!-- Generated by scripts/readme_metrics.py — do not edit by hand.
     Run `python scripts/readme_metrics.py --write` after any pipeline run. -->

All figures below are read straight out of the committed artifacts by
`scripts/readme_metrics.py`, which CI re-runs in `--check` mode. If a model
changes and this section is not regenerated, the build fails. Dataset:
**{meta["dataset"]}**, {meta["n_rows"]:,} customers.

### Per-segment churn models

| Segment | Customers | Churn rate | Holdout AUC | Train AUC | Holdout Brier (raw → calibrated) | Trees |
|---|---|---|---|---|---|---|
{chr(10).join(rows)}

**Mean holdout AUC {mean_holdout:.3f}**, against {mean_train:.3f} on the rows the
models were fitted on. That gap is the honest one, and reporting the holdout
number is the whole point of the split — an earlier version of this README
quoted 0.789–0.859, which were neither: they were carried over from a run on a
different dataset, next to customer counts that had been updated.

An AUC in the low 0.6s is a modest model, and it is what this data supports.
Cell2Cell churn is famously hard — the published benchmark literature sits in
roughly the same range — and the per-segment split makes it harder still by
giving each model a fifth of the rows and a narrower slice of variation.

### What calibration is worth

**Brier {brier_raw:.4f} → {brier_cal:.4f}** on held-out rows, a
{(1 - brier_cal / brier_raw) * 100:.0f}% reduction. Calibration cannot change
AUC — it is a monotone map, so the ranking is identical by construction — which
is exactly why the pair of Brier scores is the number that means anything.

The clearest way to see it: predicted churn now averages
**{df["ChurnProbability"].mean():.4f}** against an actual churn rate of
**{df["Churn"].mean():.4f}**. Uncalibrated, these models are trained with
`class_weights=[1, pos_weight]`, which inflates the positive class on purpose,
and their probabilities are then multiplied by CLV to rank retention spend.

This is also why only **{tiers.get("High Risk", 0):,} customers** are High Risk
(calibrated P(churn) ≥ 0.6) rather than the tens of thousands an earlier version
of this README reported. That larger figure was not a finding; it was the
weighting artifact, read as risk.

| Risk tier | Customers |
|---|---|
| High Risk (≥ 0.60) | {tiers.get("High Risk", 0):,} |
| Medium Risk (0.30–0.60) | {tiers.get("Medium Risk", 0):,} |
| Low Risk (< 0.30) | {tiers.get("Low Risk", 0):,} |

### Segmentation stability

Bootstrap Adjusted Rand Index over {stability["n_bootstrap"]} resamplings:
**mean ARI {stability["mean_ari"]:.3f} ± {stability["std_ari"]:.3f}** —
*{stability["grade"]}*. The resampling draws from a seeded generator, so this
figure is reproducible; it previously used NumPy's global RNG and moved on every
run while the README quoted it to three decimals.

### Uplift and the four quadrants

| Customer type | Count | Meaning |
|---|---|---|
| Persuadable | {types.get("Persuadable", 0):,} | High churn risk **and** responds to intervention — the target list |
| Sure Thing | {types.get("Sure Thing", 0):,} | Would respond, but is not at risk — no spend needed |
| Lost Cause | {types.get("Lost Cause", 0):,} | At risk, but intervention does not help |
| Sleeping Dog | {types.get("Sleeping Dog", 0):,} | Not at risk, and contact makes things worse — do not disturb |

`UpliftScore` is `mu_0 - mu_1`: **positive means the intervention reduces this
customer's churn probability.** That convention is checked against observed
outcomes on every run rather than assumed. Among customers who were actually
treated, the top uplift decile churns at
**{direction.get("churn_top_uplift_decile", float("nan")):.4f}** against the
bottom decile's **{direction.get("churn_bottom_uplift_decile", float("nan")):.4f}**
— the right way round, and the pipeline fails loudly if it ever is not.

It was not the right way round. CausalML's meta-learners return `mu_1 - mu_0`,
the treatment effect on the *outcome*, and the raw output was used unnegated.
The outcome here is churn, so a large positive score marked the customers
contact was expected to drive away — and `classify_customer_type` read it as
"responds well". Every name on the Persuadable list was the model's strongest
Sleeping Dog, and the AI agent wrote retention plans for all of them. The sign
error produced a ranked list, sensible-looking ROI figures and a full dashboard,
which is why it survived: nothing about it looked wrong.

**Treatment is observational, not experimental.** `Complain` and `CouponUsed`
are proxies for having received outreach, so these are associations under an
assumption of no unmeasured confounding, not causal estimates. Production uplift
models train on randomised experiment logs. The direction check above shares
every confound of the proxy — it catches a flipped sign, which is what it is
for, and it is not evidence of an effect size.
{END}"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the README section")
    parser.add_argument("--check", action="store_true", help="fail if the README is stale")
    args = parser.parse_args()

    section = build_section()

    if not (args.write or args.check):
        print(section)
        return 0

    with open(README, encoding="utf-8") as fh:
        readme = fh.read()

    if START not in readme or END not in readme:
        print(f"error: {README} has no {START} / {END} markers.", file=sys.stderr)
        return 2

    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + section + tail

    if args.check:
        if updated != readme:
            print(
                "README results section is out of date with the committed artifacts.\n"
                "Run: python scripts/readme_metrics.py --write",
                file=sys.stderr,
            )
            return 1
        print("README results section matches the artifacts.")
        return 0

    with open(README, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print("README results section regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
